sudo: required
services:
  - docker
before_install:
  - docker build -t rupeshpanwar/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run  -e CI=true rupeshpanwar/react-test npm run test -- --coverage

after_success:
  - docker build -t rupeshpanwar/multi-client ./client
  - docker build -t rupeshpanwar/multi-nginx ./nginx
  - docker build -t rupeshpanwar/multi-server ./server
  - docker build -t rupeshpanwar/multi-worker ./worker
  # Login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rupeshpanwar/multi-client
  - docker push rupeshpanwar/multi-nginx
  - docker push rupeshpanwar/multi-server
  - docker push rupeshpanwar/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-075890588897"
  bucket_path: "docker-multi"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true




















# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-075890588897"
#   bucket_path: "docker-react"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY